// Code generated by mockery v0.0.0-dev. DO NOT EDIT.

package mocks

import (
	model "github.com/erizaver/etherium_proxy/internal/pkg/model"
	mock "github.com/stretchr/testify/mock"
)

// EthClient is an autogenerated mock type for the EthClient type
type EthClient struct {
	mock.Mock
}

// GetBlockByNumber provides a mock function with given fields: blockId
func (_m *EthClient) GetBlockByNumber(blockId string) (*model.Block, error) {
	ret := _m.Called(blockId)

	var r0 *model.Block
	if rf, ok := ret.Get(0).(func(string) *model.Block); ok {
		r0 = rf(blockId)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*model.Block)
		}
	}

	var r1 error
	if rf, ok := ret.Get(1).(func(string) error); ok {
		r1 = rf(blockId)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}
